# .github/workflows/release.yml
name: Create ChatControl Release

# ... (o início do arquivo continua o mesmo) ...
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Compilar e Instalar a dependência 'Foundation'
        run: |
          echo "Clonando e instalando a biblioteca Foundation para resolver a dependência..."
          git clone https://github.com/kangarko/Foundation.git
          cd Foundation
          mvn -B install -DskipTests

      # --- ALTERAÇÃO AQUI ---
      - name: Build with Maven
        run: >
          mvn -B package
          -pl chatcontrol-bukkit
          -am

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_info.outputs.tag_name }}
          body: ${{ steps.get_info.outputs.changelog }}
          # O JAR final estará dentro da pasta "target" do módulo "chatcontrol-bukkit"
          files: chatcontrol-bukkit/target/ChatControl-Pro-*.jar
