# .github/workflows/release.yml
name: Create ChatControl Release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Define Tag e Busca Changelog
        id: get_info
        # ... (este passo permanece o mesmo)
        run: |
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            TAG_NAME="${{ github.ref_name }}"
          else
            TAG_NAME=$(gh api repos/kangarko/ChatControl/releases/latest --jq '.tag_name')
          fi
          echo "tag_name=$TAG_NAME" >> "$GITHUB_OUTPUT"
          CHANGELOG_BODY=$(gh api repos/kangarko/ChatControl/releases/tags/$TAG_NAME --jq '.body' 2>/dev/null) || true
          if [[ -z "$CHANGELOG_BODY" ]]; then
            CHANGELOG_BODY="Nenhum changelog oficial encontrado para esta tag."
          fi
          cat <<EOF >> "$GITHUB_OUTPUT"
          changelog<<HEREDOC
          $CHANGELOG_BODY
          HEREDOC
          EOF
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      # ---- NOVO PASSO ADICIONADO ----
      - name: Compilar e Instalar a dependência 'Foundation'
        run: |
          echo "Clonando e instalando a biblioteca Foundation para resolver a dependência..."
          git clone https://github.com/kangarko/Foundation.git
          cd Foundation
          # O comando 'install' compila e coloca a biblioteca no cache local do Maven
          # O -DskipTests acelera o processo por não rodar os testes da biblioteca
          mvn -B install -DskipTests

      - name: Build with Maven
        # Este passo agora vai funcionar, pois encontrará a dependência 'Foundation' localmente
        run: mvn -B package --file pom.xml

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_info.outputs.tag_name }}
          body: ${{ steps.get_info.outputs.changelog }}
          files: target/ChatControl-Pro-*.jar
