name: Create ChatControl Release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Define Tag e Busca Changelog
        id: get_info
        run: |
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            TAG_NAME="${{ github.ref_name }}"
            echo "Workflow acionado pela tag: $TAG_NAME"
          else
            echo "Workflow acionado manualmente. Buscando última tag do projeto original..."
            # ALTERADO: Aponta para o novo repositório
            TAG_NAME=$(gh api repos/kangarko/ChatControl/releases/latest --jq '.tag_name')
            echo "Última tag encontrada: $TAG_NAME"
          fi

          echo "tag_name=$TAG_NAME" >> "$GITHUB_OUTPUT"

          echo "Buscando changelog para a tag: $TAG_NAME"
          # ALTERADO: Aponta para o novo repositório
          CHANGELOG_BODY=$(gh api repos/kangarko/ChatControl/releases/tags/$TAG_NAME --jq '.body' 2>/dev/null) || true

          if [[ -z "$CHANGELOG_BODY" ]]; then
            CHANGELOG_BODY="Nenhum changelog oficial encontrado para esta tag. Verifique o histórico de commits para detalhes."
          fi
          
          cat <<EOF >> "$GITHUB_OUTPUT"
          changelog<<HEREDOC
          $CHANGELOG_BODY
          HEREDOC
          EOF
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          # ALTERADO: ChatControl-Pro usa Java 17
          java-version: '17'
          distribution: 'temurin'
          # Adiciona cache para o Maven para acelerar builds futuras
          cache: 'maven'

      - name: Build with Maven
        # ALTERADO: Comando de build para Maven
        # O "-B" é para modo batch (não interativo) e "package" compila e empacota o JAR.
        run: mvn -B package --file pom.xml

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_info.outputs.tag_name }}
          body: ${{ steps.get_info.outputs.changelog }}
          # ALTERADO: O Maven gera os arquivos na pasta 'target'.
          # O nome do JAR do ChatControl Pro segue este padrão.
          files: target/ChatControl-Pro-*.jar
